packages:
  - apps/*
  - packages/*
allowBuilds:
  '@swc/core': true
catalog:
  dotenv: ^17.4.2
  zod: ^4.4.3
  "@types/node": ^26.2.0
  "@orpc/server": ^1.15.0
  "@orpc/openapi": ^1.15.0
  "@orpc/zod": ^1.15.0
  better-auth: 1.6.22
  vitest: 4.1.8
  "@vitest/ui": 4.1.8
  "@vitest/coverage-v8": 4.1.8
  jsdom: ^29.1.1
  "@orpc/client": ^1.15.0
  "@prisma/client": ^7.9.1
